[build]
  # Publish from the project root (contains index.html and app-ads.txt)
  publish = "."
  # No build command needed for static HTML/CSS/JS
  command = ""

# Ensure app-ads.txt is served with the correct content type
[[headers]]
  for = "/app-ads.txt"
  [headers.values]
    Content-Type = "text/plain"

# (Optional) Uncomment to enable Single Page App routing
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
#   force = true